name: Deprecate
on: 
  workflow_dispatch:
   inputs:
      versionRange:
        description: 'A version to deprecate - https://docs.npmjs.com/cli/v8/configuring-npm/package-json#dependencies'
        required: true
        type: string
      reasonMessage:
        description: "A reason why those versions must be marked as deprecated - e.g. critical bug fixed in v0.2.3\nIf left empty it will un deprecate version"
        required: false
        type: string
jobs:
  deprecate-package-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: npm deprecate
        run: npm deprecate generic-interceptor@${{ github.event.inputs.versionRange }} "${{ github.event.inputs.reasonMessage }}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_GITHUB_ACTIONS_GENERIC_INTERCEPTOR_PUBLISH }}
